export const AppData = {
  logo: "/logewithname.png",
  popularStocks: [
    {
      name: "Nifty bank",
      price: "41,559.40",
      changePercentage: "0.01%",
      profit: true,
    },
    {
      name: "Bajfinance",
      price: "6,435.50",
      changePercentage: "0.30%",
      profit: false,
    },
    {
      name: "Bhartiatl",
      price: "771.95",
      changePercentage: "0.69%",
      profit: true,
    },
    {
      name: "HdfcBank",
      price: "1,657.10",
      changePercentage: "0.40%",
      profit: true,
    },
    {
      name: "Hindunilvr",
      price: "2,577.50",
      changePercentage: "0.36%",
      profit: false,
    },
    {
      name: "Indigo",
      price: "2,043.50",
      changePercentage: "9.21%",
      profit: false,
    },
    {
      name: "Ishant",
      price: "8,441.50",
      changePercentage: "24.21%",
      profit: true,
    },
  ],
  featuredCompanies: [
    "/caprinew1.jpg",
    "/ganeshhousing.jpg",
    "/fino.png",
    "/gravita.jpg",
    "/godawari.jpg",
    "/dtpatten1.png",
    "/deepind.png",
  ],
  posts: [
    {
      image: "/stock1.jpg",
      userProfile: "/avatar.png",
      userName: "Lorem ipsum",
      sector: 1,
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industury.",
      likes: "2k",
      views: "2k",
      comments: "2k",
      timeAgo: "2min ago",
    },
    {
      image: null,
      userProfile: "/avatar.png",
      userName: "Lorem ipsum",
      sector: 2,
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industury.",
      likes: "1k",
      views: "7k",
      comments: "3k",
      timeAgo: "5min ago",
    },
    {
      image: null,
      userProfile: "/avatar.png",
      userName: "Lorem ipsum",
      sector: 3,
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industury.",
      likes: "9k",
      views: "3k",
      comments: "3k",
      timeAgo: "10min ago",
    },
    {
      image: "/stock1.jpg",
      userProfile: "/avatar.png",
      userName: "Lorem ipsum",
      sector: 1,
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industury.",
      likes: "2k",
      views: "2k",
      comments: "2k",
      timeAgo: "2min ago",
    },
    {
      image: null,
      userProfile: "/avatar.png",
      userName: "Lorem ipsum",
      sector: 2,
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industury.",
      likes: "1k",
      views: "7k",
      comments: "3k",
      timeAgo: "5min ago",
    },
    {
      image: null,
      userProfile: "/avatar.png",
      userName: "Lorem ipsum",
      sector: 3,
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industury.",
      likes: "9k",
      views: "3k",
      comments: "3k",
      timeAgo: "10min ago",
    },
  ],
};
